version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./rules.yaml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
